# Generated by Django 3.0.8 on 2020-07-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.Product'),
        ),
    ]
